<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.adobexp</groupId>
        <artifactId>aem-dam-asset-picker</artifactId>
        <version>1.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>aem-dam-asset-picker.ui.content</artifactId>
    <packaging>content-package</packaging>
    <name>AEM DAM Asset Picker - UI content</name>
    <description>Demo pages and conf for the Asset Picker</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.jackrabbit</groupId>
                <artifactId>filevault-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <properties>
                        <cloudManagerTarget>none</cloudManagerTarget>
                    </properties>
                    <group>com.adobexp</group>
                    <name>aem-dam-asset-picker.ui.content</name>
                    <packageType>content</packageType>
                    <accessControlHandling>ignore</accessControlHandling>
                    <repositoryStructurePackages>
                        <repositoryStructurePackage>
                            <groupId>com.adobexp</groupId>
                            <artifactId>aem-dam-asset-picker.ui.apps.structure</artifactId>
                        </repositoryStructurePackage>
                    </repositoryStructurePackages>
                    <validatorsSettings>
                        <jackrabbit-filter>
                            <options>
                                <validRoots>/conf,/content,/content/dam,/content/asset-picker,/etc,/etc/acs-commons,/etc/acs-commons/lists</validRoots>
                            </options>
                        </jackrabbit-filter>
                    </validatorsSettings>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <verbose>true</verbose>
                    <failOnError>true</failOnError>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.adobexp</groupId>
            <artifactId>aem-dam-asset-picker.ui.apps</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
        <dependency>
            <groupId>com.adobexp</groupId>
            <artifactId>aem-dam-asset-picker.ui.apps.structure</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
    </dependencies>
</project>
